nelmio_api_doc:
    documentation:
        info:
            title: Swagger para los EndPoints de la aplicación DailyTrends
            description: Se incluyen los distintos Endpoints que serviran para añadir, eliminar o actualizar un feed de portada del periodico el Mundo o el País
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc$)