# Swagger UI
api_doc_ui:
    path: /api/doc
    controller: nelmio_api_doc.controller.swagger_ui
    defaults:
        area: default

# OpenAPI JSON
api_doc_json:
    path: /api/doc.json
    controller: nelmio_api_doc.controller.swagger_json
    defaults:
        area: default